// Authentication for the WooCommerce facade.
//
// The supplier's system (Dianxiaomi) only knows how to talk to a WooCommerce
// store, so it authenticates the way WooCommerce does: a consumer key and a
// consumer secret, sent either as HTTP Basic auth or as query parameters. Both
// are accepted here because different clients pick different ones.
//
// These are OUR credentials, generated by us and handed to the supplier. They
// live in the environment, never in the database and never in a log line.

import { timingSafeEqual } from "node:crypto";

/** Constant time, so a wrong secret cannot be found one character at a time. */
function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a, "utf8");
  const bufB = Buffer.from(b, "utf8");
  if (bufA.length !== bufB.length) {
    // Still compare something of equal length, so the failure takes the same
    // time whether the length or the content is wrong.
    timingSafeEqual(bufA, bufA);
    return false;
  }
  return timingSafeEqual(bufA, bufB);
}

export function isWooConfigured(): boolean {
  return Boolean(
    process.env.WOO_CONSUMER_KEY && process.env.WOO_CONSUMER_SECRET,
  );
}

type Credentials = { key: string; secret: string };

function fromBasicAuth(header: string | null): Credentials | null {
  if (!header?.startsWith("Basic ")) return null;
  try {
    const decoded = Buffer.from(header.slice(6), "base64").toString("utf8");
    const separator = decoded.indexOf(":");
    if (separator === -1) return null;
    return {
      key: decoded.slice(0, separator),
      secret: decoded.slice(separator + 1),
    };
  } catch {
    return null;
  }
}

function fromQuery(url: URL): Credentials | null {
  const key = url.searchParams.get("consumer_key");
  const secret = url.searchParams.get("consumer_secret");
  return key && secret ? { key, secret } : null;
}

export function authenticateWooRequest(request: Request): boolean {
  if (!isWooConfigured()) return false;

  const url = new URL(request.url);
  const provided =
    fromBasicAuth(request.headers.get("authorization")) ?? fromQuery(url);
  if (!provided) return false;

  const keyOk = safeEqual(provided.key, process.env.WOO_CONSUMER_KEY!);
  const secretOk = safeEqual(provided.secret, process.env.WOO_CONSUMER_SECRET!);
  // Both are always evaluated so the answer takes the same time either way.
  return keyOk && secretOk;
}

/** Query string with the credentials stripped, safe to write to the log. */
export function redactedQuery(url: URL): string | null {
  const params = new URLSearchParams(url.search);
  for (const name of ["consumer_key", "consumer_secret"]) {
    if (params.has(name)) params.set(name, "[redacted]");
  }
  const query = params.toString();
  return query.length > 0 ? query : null;
}
